#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
ag_ai — PRD (Product Requirements Document) Generator
Auto-generates PRD.md from wizard-answers.json + context files.

Usage:
  python prd.py [project_path]
  python prd.py [project_path] --regenerate   overwrite existing PRD.md
"""

import sys, json
from pathlib import Path
from datetime import datetime

if sys.platform == "win32":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stdin.reconfigure(encoding="utf-8", errors="replace")

BOLD="\033[1m"; GREEN="\033[92m"; YELLOW="\033[93m"
RED="\033[91m"; CYAN="\033[96m"; RESET="\033[0m"

REGENERATE = "--regenerate" in sys.argv

def ok(msg):   print(f"  {GREEN}OK  {msg}{RESET}")
def warn(msg): print(f"  {YELLOW}--  {msg}{RESET}")
def err(msg):  print(f"  {RED}XX  {msg}{RESET}")


def get_project_path():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if args:
        return Path(args[0]).resolve()
    try:
        raw = input(f"{CYAN}  -> Project path (Enter = current dir): {RESET}").strip()
        return Path(raw).resolve() if raw else Path.cwd()
    except (EOFError, KeyboardInterrupt):
        return Path.cwd()


def load_wizard_answers(project_path):
    """Load wizard-answers.json, return dict or None."""
    answers_file = project_path / ".ai/context/wizard-answers.json"
    if not answers_file.exists():
        return None
    try:
        return json.loads(answers_file.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError) as e:
        warn(f"Could not parse wizard-answers.json: {e}")
        return None


def load_context_file(project_path, rel_path):
    """Read a context file, return content or empty string."""
    fp = project_path / rel_path
    if fp.exists():
        try:
            return fp.read_text(encoding="utf-8")
        except OSError:
            return ""
    return ""


def generate_prd(answers, project_path):
    """Build PRD.md content from wizard answers + context."""

    name         = answers.get("name", "Untitled Project")
    description  = answers.get("description", "No description provided")
    proj_type    = answers.get("type", "web").capitalize()
    status       = answers.get("status", "new").capitalize()
    out_of_scope = answers.get("out_of_scope", "Not defined yet")
    backend      = answers.get("backend", "Unknown")
    db_engine    = answers.get("db_engine", "Unknown")
    db_name      = answers.get("db_name", "Unknown")
    frontend     = answers.get("frontend", "Unknown")
    local        = answers.get("local", "Unknown")
    integrations = answers.get("integrations", [])
    hard_rules   = answers.get("hard_rules", "")
    language     = answers.get("language", "English")
    ai_tool      = answers.get("ai_tool", "both")

    integ_list = "\n".join(f"- {i}" for i in integrations) if integrations else "- None"
    hard_block = f"- {hard_rules}" if hard_rules and hard_rules.strip() else "- No additional rules defined"
    today = datetime.now().strftime("%Y-%m-%d")

    # Detect existing features in specs/
    specs_dir = project_path / "specs"
    features = []
    if specs_dir.exists():
        features = sorted([d.name for d in specs_dir.iterdir() if d.is_dir()])
    features_block = "\n".join(f"- `specs/{f}/`" for f in features) if features else "- No features specified yet — run `/speckit.specify` or `spec-workflow` agent"

    return f"""# PRD — {name}

> Auto-generated by ag_ai on {today}. Regenerate: `python prd.py [path] --regenerate`

---

## 1. Product Overview

| Field | Value |
|-------|-------|
| **Name** | {name} |
| **Type** | {proj_type} |
| **Status** | {status} |
| **Description** | {description} |
| **Out of Scope** | {out_of_scope} |
| **Docs Language** | {language} |

---

## 2. Tech Stack

| Layer | Technology |
|-------|-----------|
| **Backend** | `{backend}` |
| **Database** | `{db_engine}` — `{db_name}` |
| **Frontend** | `{frontend}` |
| **Local Dev** | `{local}` |

### Integrations
{integ_list}

---

## 3. Business Rules

{hard_block}

### Non-Negotiable (all projects)
- NEVER hardcode credentials, tokens, or API keys
- NEVER use `SELECT *` in production
- ALWAYS validate user input at the boundary
- ALWAYS use parameterized SQL queries

---

## 4. Features & Specs

{features_block}

### Spec Workflow (how to add features)
```
Step 1 → spec-workflow agent: /speckit.specify [feature description]
Step 2 → spec-workflow agent: /speckit.clarify
Step 3 → spec-workflow agent: /speckit.plan
Step 4 → spec-workflow agent: /speckit.tasks
Step 5 → spec-workflow agent: /speckit.implement
```

Each feature lives in `specs/{{###-feature-name}}/` with:
`spec.md` → `plan.md` → `data-model.md` → `tasks.md`

---

## 5. Agent Routing

| Task | Agent | Tool Access |
|------|-------|-------------|
| Complex multi-step | `orchestrator` | read, glob, grep, task |
| Spec-first planning | `spec-workflow` | full |
| System design | `architect` | read, write, glob, grep |
| Write / refactor code | `coder` | full |
| TDD implementation | `tdd-guide` | full |
| Database schema | `db-agent` | full |
| API endpoints | `api-agent` | full |
| Code review | `code-reviewer` | read, write, glob, grep |
| Security audit | `security-reviewer` | full |
| DB review | `database-reviewer` | read, write, glob, grep |
| Refactoring | `refactor-cleaner` | full |
| Build errors | `build-error-resolver` | full |
| Documentation | `doc-updater` | read, write, edit, glob, grep |
| SQL queries | `sql-helper` | full |
| Telegram bot | `telegram-bot` | full |
| n8n workflows | `n8n-workflow` | full |
| Debugging | `debugger` | full |
| Tests | `test-writer` | full |

---

## 6. Reading Chain — What Agents Read First

```
PRD.md                    ← YOU ARE HERE — product overview
  └→ AGENTS.md            ← agent routing + rules
  └→ .ai/context/STACK.md ← tech stack details
  └→ .ai/context/RULES.md ← coding rules
  └→ .ai/spec/memory/constitution.md ← project principles
```

### File Map
| File | Purpose |
|------|---------|
| `PRD.md` | Product requirements (this file) |
| `AGENTS.md` | Agent routing table + non-negotiable rules |
| `CLAUDE.md` | Claude Code entry point |
| `.ai/agents/*.md` | 18 agent instruction files |
| `.ai/rules/common.md` | Universal coding style + security |
| `.ai/rules/php.md` | PHP architecture + security + testing |
| `.ai/context/PROJECT.md` | Project description |
| `.ai/context/STACK.md` | Tech stack + env variables |
| `.ai/context/RULES.md` | Project-specific coding rules |
| `.ai/spec/commands.md` | Spec Kit commands reference |
| `.ai/spec/templates/` | Spec, plan, tasks templates |
| `.ai/spec/memory/constitution.md` | Project principles |
"""


def main():
    print(f"\n{BOLD}  ag_ai — PRD Generator{RESET}")

    project_path = get_project_path()
    print(f"  Project: {project_path}\n")

    prd_file = project_path / "PRD.md"
    if prd_file.exists() and not REGENERATE:
        warn("PRD.md already exists. Use --regenerate to overwrite.")
        return 0

    answers = load_wizard_answers(project_path)
    if not answers:
        err("No wizard-answers.json found.")
        err("Run the wizard first:  python wizard.py [project_path]")
        return 1

    prd_content = generate_prd(answers, project_path)
    prd_file.write_text(prd_content, encoding="utf-8")
    ok(f"PRD.md generated ({len(prd_content)} bytes)")

    print(f"\n{GREEN}{BOLD}  Done! PRD.md is ready at: {prd_file}{RESET}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
